{% set name = "django-ipware" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 176fddb27d8d0f96fe3872fe03a781ea96638553e05842d89c12a3dd9bedf5f5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - django

about:
  home: https://pypi.org/project/django-axes/
  summary: django-ipware, application to retrieve client's IP address.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
