{% set name = "django-ipware" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0233341eddcc19de44f463dd3e53c87ef9dcc519fc74a99911cebe9b58197549

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - python-ipware >=2.0.0

about:
  home: https://pypi.org/project/django-ipware/
  summary: This is django-ipware, application to retrieve client's IP address.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
