{% set name = "django-ipware" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9ec43d2bf7cdf216fed8d494a084deb5761a54860a53b2e74346a4f384cff47

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - django
    - python-ipware >=2.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipware

about:
  home: https://pypi.org/project/django-ipware/
  summary: This is django-ipware, application to retrieve client's IP address.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
